[env]
TERM = "xterm-256color"

[window]
opacity = 0.75

padding.x = 8
padding.y = 8

[font]
normal.family = "SF Mono Powerline"
normal.style = "Medium"
bold.family = "SF Mono Powerline"
bold.style = "Bold"
size = 12

[cursor]
style.shape = "Block"
style.blinking = "Never"
vi_mode_style.shape = "Block"

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = false

# MOONFLY

 [colors.bright]
 black = "#949494"
 blue = "#74b2ff"
 cyan = "#85dc85"
 green = "#36c692"
 magenta = "#ae81ff"
 red = "#ff5189"
 white = "#e4e4e4"
 yellow = "#c2c292"

 [colors.cursor]
 cursor = "#f0f0f0"
 text = "#080808"

 [colors.normal]
 black = "#343434"
 blue = "#80a0ff"
 cyan = "#79dac8"
 green = "#8cc85f"
 magenta = "#cf87e8"
 red = "#ff5454"
 white = "#c6c6c6"
 yellow = "#e3c78a"

 [colors.primary]
 background = "#080808"
 bright_foreground = "#ffffff"
 foreground = "#ededed"

 [colors.selection]
 background = "#b2ceee"
 text = "#080808"
