[pyprland]
plugins = ["scratchpads", "lost_windows", "magnify", "expose"]

[expose]
include_special = false

[scratchpads.volume]
animation = "fromTop"
command = "flatpak run com.saivert.pwvucontrol"
class = "com.saivert.pwvucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.spotify]
animation = "fromTop"
command = "com.github.KRTirtho.Spotube"
class = "spotube"
lazy = true
size = "60% 70%"
unfocus = "hide"
match_by = "class"

[scratchpads.password]
animation = "fromTop"
command = "com.bitwarden.desktop"
class = "Bitwarden"
lazy = true
size = "50% 60%"
unfocus = "hide"
match_by = "class"
