[pyprland]
plugins = ["scratchpads", "lost_windows", "magnify", "expose"]

[expose]
include_special = false

[scratchpads.volume]
animation = "fromTop"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "50% 60%"
unfocus = "hide"

[scratchpads.music]
animation = "fromTop"
command = "LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify"
class = "Spotify"
lazy = true
size = "60% 70%"
unfocus = "hide"
class_match = true

[scratchpads.password]
animation = "fromTop"
command = "flatpak run com.bitwarden.desktop"
class = "Bitwarden"
lazy = true
size = "50% 60%"
class_match = true
