[config]
folderIcon = "T"
menu = "tofi"

[bookmarks]
urls = [
  "This repo # https://github.com/m4rti21/book",
  "This repo # https://git.m4rti.dev/book",
  "This is a test # https://m4rti.dev",
  "This is another test # https://wysi727.com",
]

arch.urls = [
  "This is a test # https://archlinux.org",
  "This is another test # https://artixlinux.org",
]

debian.urls = [
  "https://debian.org",
  "https://ubuntu.org",
  "https://linuxmint.com",
]

debian.stuff.urls = [
  "https://test1.com",
  "https://test2.org",
  "https://test3.org",
]

debian.stuff."more stuff".urls = [
  "https://test1.com",
  "https://test2.org",
  "https://test3.org",
]
