#!/bin/sh
# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
    # If non-first battery, print a space separator.
    [ -n "${capacity+x}" ] && printf " "
    # Sets up the status and capacity
    case "$(cat "$battery/status" 2>&1)" in
    "Full") status="󰁹" ;;
    "Discharging") status="󰁼" ;;
    "Charging") status="󰂄" ;;
    "Not charging") status="󰂃" ;;
    "Unknown") status="" ;;
    *) exit 1 ;;
    esac
    capacity="$(cat "$battery/capacity" 2>&1)"
    # Prints the info
    printf "%s %d%%" "$status" "$capacity"
    unset warn
done && printf "\\n"
