#!/bin/sh

# Check if any battery directories exist
if [ -z "$(ls /sys/class/power_supply)" ]; then
    exit 1
fi

# Check if there are any battery directories (BAT*)
if [ -z "$(ls /sys/class/power_supply/BAT?*)" ]; then
    exit 1
fi

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
    # If non-first battery, print a space separator.
    [ -n "${capacity+x}" ] && printf " "

    # Set up the status and capacity
    case "$(cat "$battery/status" 2>&1)" in
    "Full") status="*" ;;
    "Discharging") status="-" ;;
    "Charging") status="+" ;;
    "Not charging") status="!" ;;
    "Unknown") status="?" ;;
    *) exit 1 ;;
    esac

    capacity="$(cat "$battery/capacity" 2>&1)"

    # Print the info
    printf " %s%d%%" "$status" "$capacity"
done && printf "\\n"
