#!/bin/sh

SCREENSHOT_DIR=~/Pictures/screenshots
fullscreen=""

while getopts ":f" opt; do
    case ${opt} in
    f)
        fullscreen="true"
        ;;
    \?)
        notify_error "Invalid option: -$OPTARG"
        usage
        ;;
    :)
        notify_error "Invalid option: -$OPTARG requires an argument"
        usage
        ;;
    esac
done
shift $((OPTIND - 1))

XDG_CURRENT_DESKTOP=sway
IMG_NAME="$SCREENSHOT_DIR/screenshot_$(date '+%Y-%m-%d_%H-%M-%S').png"

if [ "$fullscreen" = "true" ]; then
    flameshot full --raw >$IMG_NAME
else
    flameshot gui --raw >$IMG_NAME
fi

wl-copy <$IMG_NAME
notify-send --icon="$IMG_NAME" "Screenshot copied!" "$IMG_NAME"

# if [ "$fullscreen" = "true" ]; then
#     grim -g "$(slurp -o -d)" $IMG_NAME
# else
#     grim -g "$(slurp -d)" $IMG_NAME
# fi
#
# wl-copy <$IMG_NAME
#
# notify-send --icon="$IMG_NAME" "Screenshot copied!" "$IMG_NAME"
