#!/bin/sh

SCREENSHOT_DIR=~/Pictures/screenshots

fullscreen=""

while getopts ":f" opt; do
    case ${opt} in
    f)
        fullscreen="true"
        ;;
    \?)
        notify_error "Invalid option: -$OPTARG"
        usage
        ;;
    :)
        notify_error "Invalid option: -$OPTARG requires an argument"
        usage
        ;;
    esac
done
shift $((OPTIND - 1))

IMG_NAME="$SCREENSHOT_DIR/$(date '+%Y-%m-%d-%H%M%S').png"

if [ "$fullscreen" = "true" ]; then
    grim -g "$(slurp -o -d)" $IMG_NAME
else
    grim -g "$(slurp -d)" $IMG_NAME
fi

wl-copy <$IMG_NAME

notify-send --icon="$IMG_NAME" "Screenshot copied!" "$IMG_NAME"
